### ISSUE TITLE
form questions

### ISSUE THREAD

**Issue by zielhl** [staciekoslovsky-noaa/BodyCondition_DataManagement#1]
Hi all - I just came up with a few questions and things to talk about when looking at the DB forms.

1. Do you think we should add CD# to the Aircraft table?
2. Will you look over the Aircraft Identifiers I came up with - then we can change them if we want to?
3. It would be good to talk about how to make the Target Identifier more meaningful. I see the confusion in the drop down menu in the Images and Measurements form.
4. I'm sure this will be answered in the overview - but just so I don't forget to ask... After you add a flight to the Flight Data form, how or when does it to show up in the Images and Meas form?

**Comment by staciekoslovsky-noaa** [comment]
My responses to each of your points above.
1. I went ahead and added a CD number to the aircraft table...I think that's a great idea! The new database version is on the network.
2. They look good to me, but I'll leave this one mostly up to others.
3. I have some ideas on this, but I want to let others weigh in first.
4. The relationship gets made between the flight data and the images after both are imported (images) and entered (field data) into the database. I have a script set up that relates the data in these two tables. Once the flight-image data are connected, you will be able to review the images, update their associated processing fields and enter the measurements into the database.
